export const CATEGORY_ICONS = [
    "category-icon-star-and-crescent-solid.png",
    "category-icon-tree-solid.png",
    "category-icon-water-solid.png",
    "category-icon-user-tie-solid.png",
    "category-icon-users-solid.png",
    "category-icon-fist-raised-solid.png",
    "category-icon-medkit-solid.png",
    "category-icon-building-solid.png",
    "category-icon-money-check-alt-solid.png",
    "category-icon-desktop-solid.png",
    "category-icon-hands-solid.png",
    "category-icon-running-solid.png",
    "category-icon-route-solid.png",
    "category-icon-briefcase-solid.png",
    "category-icon-exclamation-triangle-solid.png",
    "category-icon-city-solid.png",
    "category-icon-graduation-cap-solid.png",
    "category-icon-store-solid.png",
    "category-icon-wallet-solid.png",
    "category-icon-handshake-solid.png",
    "category-icon-lightbulb-solid.png",
    "category-icon-book-open-solid.png",
    "category-icon-gripfire-brands.png",
    "category-icon-share-alt-solid.png",
];

export const CATEGORY_NAMES = [
    "Keagamaan",
    "Kehutanan, Petanian dan Ketahanan Pangan",
    "Kelautan, Perikanan dan Peternakan",
    "Kepegawaian",
    "Kependudukan",
    "Kesatuan Bangsa dan Politik",
    "Kesehatan",
    "Ketenagakerjaan",
    "Keuangan Daerah",
    "Komunikasi dan Informasi",
    "Lingkungan Hidup",
    "Olahraga dan Pemuda",
    "Pariwisata dan Kebudayaan",
    "Pekerjaan Umum",
    "Penanggulangan Bencana",
    "Penataan Kota",
    "Pendidikan",
    "Perdagangan",
    "Perekonomian",
    "Perhubungan",
    "Perindustrian dan Energi",
    "Perpustakaan dan Arsip",
    "Pertamanan dan Pemakaman",
    "Sosial",
];

export const ORGANIZATION_PHOTO_FOR_SEEDER = "organization-photo-for-seeder.jpg";
export const DATASET_ATTACHMENT_FOR_SEEDER = "dataset-attachment-for-seeder.csv";
